### ISSUE TITLE
Event or callback on start

### ISSUE THREAD

**Issue by aemonge** [M1T0zd/Web-CLI#2]
Can we have an event or a callback on the start command. So that when it opens, i can display my help command.

Thanks in advanced ! You're awesome

**Comment by M1T0zd** [comment]
That's not a bad idea! Something like a `onConnect` function would be fitting.

**Comment by aemonge** [comment]
Awesome !

**Comment by M1T0zd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [onConnect function](https://trello.com/c/1CxPfzX1/23-onconnect-function)

**Comment by M1T0zd** [comment]
88db514726dc4622fc4e8b4b769e0f60180886ca
